version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dontapdabomb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: ghcr.io/ryanjoew/dontapdabomb-backend:latest
    container_name: dontapdabomb-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dontapdabomb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  frontend:
    image: ghcr.io/ryanjoew/dontapdabomb-frontend:latest
    container_name: dontapdabomb-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # check elke 60 seconden op nieuwe images
      WATCHTOWER_POLL_INTERVAL: 60
      # update alleen containers met de enable-label
      WATCHTOWER_LABEL_ENABLE: "true"

volumes:
  db_data:
